export const FORM_EMBED_RELATION = 'FORM_EMBED_RELATION';
export const GET_ONE_SELECTED = 'GET_ONE_SELECTED';
export const SELECTOR_INIT = 'SELECTOR_INIT';
export const SELECTOR_CLEAR = 'SELECTOR_CLEAR';
export const FORM_EMBED_RELATION_CHANGED = 'FORM_EMBED_RELATION_CHANGED';

export const actionType = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  CLONE: 'CLONE',
  USE: 'USE',
  UNLINK: 'UNLINK',
}